import type { Car } from "../cars";
import { viewsFor, type HouseSponsor, type Spot } from "../spots";
import { CYBERTRUCK_HOTSPOTS } from "./cybertruck.hotspots";

const SPOTS: Spot[] = [
  {
    id: "tailgate",
    number: 1,
    name: "Tailgate",
    tagline: "The billboard",
    description:
      "The single largest flat panel on the truck and the one every driver behind me stares at in traffic.",
    priceCents: 1049000,
    size: "150 × 55 cm",
    tier: "prime",
    heroView: "rear",
  },
  {
    id: "hood",
    number: 2,
    name: "Hood",
    tagline: "Front and centre",
    description:
      "A flat stainless slab the size of a dining table. Visible from every overpass, drone and balcony.",
    priceCents: 750000,
    size: "130 × 110 cm",
    tier: "prime",
    heroView: "front34",
  },
  {
    id: "driver-front-door",
    number: 3,
    name: "Driver front door",
    tagline: "Eye level, every stop",
    description:
      "The biggest door on the truck, read by everyone I pull up beside, park next to, or hand a coffee to.",
    priceCents: 460000,
    size: "100 × 60 cm",
    tier: "prime",
    heroView: "side",
  },
  {
    id: "driver-rear-door",
    number: 4,
    name: "Driver rear door",
    tagline: "Right behind it",
    description:
      "The rear door on the driver side. Slightly smaller than the front, same traffic, same eye level.",
    priceCents: 370000,
    size: "80 × 60 cm",
    tier: "prime",
    heroView: "side",
  },
  {
    id: "passenger-front-door",
    number: 5,
    name: "Passenger front door",
    tagline: "The kerb side",
    description:
      "Faces the pavement, the cafés, and every phone camera on it. The door people photograph.",
    priceCents: 460000,
    size: "100 × 60 cm",
    tier: "prime",
    heroView: "sidePassenger",
  },
  {
    id: "passenger-rear-door",
    number: 6,
    name: "Passenger rear door",
    tagline: "Kerb side, second row",
    description: "The rear door on the passenger side. Same exposure as the front door at a friendlier price.",
    priceCents: 370000,
    size: "80 × 60 cm",
    tier: "prime",
    heroView: "sidePassenger",
  },
  {
    id: "tonneau",
    number: 7,
    name: "Tonneau cover",
    tagline: "Visible from above",
    description:
      "The powered bed cover. The biggest surface on the truck when seen from above, and it is seen from above a lot.",
    priceCents: 500000,
    size: "180 × 120 cm",
    tier: "standard",
    heroView: "top",
  },
  {
    id: "nose",
    number: 8,
    name: "Nose panel",
    tagline: "Under the light bar",
    description:
      "The stainless face across the front, right under the full-width light bar. The first thing oncoming traffic sees.",
    priceCents: 420000,
    size: "200 × 35 cm",
    tier: "standard",
    heroView: "front",
  },
  {
    id: "windshield",
    number: 9,
    name: "Windshield banner",
    tagline: "Always in frame",
    description:
      "A strip across the top of the windshield. It is in every photo anyone takes of the front of this truck.",
    priceCents: 370000,
    size: "120 × 15 cm",
    tier: "standard",
    heroView: "front",
  },
  {
    id: "driver-bed",
    number: 10,
    name: "Driver side bed panel",
    tagline: "The rear quarter",
    description:
      "The long panel behind the rear door on the driver side. Large, flat, and impossible to miss when I merge.",
    priceCents: 330000,
    size: "120 × 50 cm",
    tier: "standard",
    heroView: "side",
  },
  {
    id: "passenger-bed",
    number: 11,
    name: "Passenger side bed panel",
    tagline: "Mirror of the above",
    description: "The passenger side counterpart. Identical dimensions, kerb side exposure.",
    priceCents: 330000,
    size: "120 × 50 cm",
    tier: "standard",
    heroView: "sidePassenger",
  },
  {
    id: "driver-fender",
    number: 12,
    name: "Driver front fender",
    tagline: "Over the front wheel",
    description:
      "The stainless shoulder between the nose and the driver door. Best suited to a wide wordmark.",
    priceCents: 290000,
    size: "90 × 40 cm",
    tier: "standard",
    heroView: "front34",
  },
  {
    id: "passenger-fender",
    number: 13,
    name: "Passenger front fender",
    tagline: "Over the other one",
    description: "The passenger side shoulder. Same shape, same wide-format brief, kerb side.",
    priceCents: 290000,
    size: "90 × 40 cm",
    tier: "standard",
    heroView: "sidePassenger",
  },
  {
    id: "driver-sail",
    number: 14,
    name: "Driver sail panel",
    tagline: "The sloping one",
    description:
      "The long sloped panel from the rear window down to the tailgate on the driver side. Unique to this truck.",
    priceCents: 250000,
    size: "110 × 45 cm",
    tier: "bargain",
    heroView: "side",
  },
  {
    id: "passenger-sail",
    number: 15,
    name: "Passenger sail panel",
    tagline: "The other slope",
    description: "The passenger side sail. Reads best from the kerb and from anything taller than the truck.",
    priceCents: 250000,
    size: "110 × 45 cm",
    tier: "bargain",
    heroView: "rear34",
  },
  {
    id: "front-bumper",
    number: 16,
    name: "Front bumper",
    tagline: "Low and forward",
    description: "The dark lower fascia across the nose. Perfect for a wide wordmark in a light colour.",
    priceCents: 250000,
    size: "110 × 18 cm",
    tier: "bargain",
    heroView: "front",
  },
  {
    id: "rear-bumper",
    number: 17,
    name: "Rear bumper",
    tagline: "The chasing view",
    description: "The panel under the tailgate. Read by everyone who is stuck behind me, which is most people.",
    priceCents: 250000,
    size: "110 × 18 cm",
    tier: "bargain",
    heroView: "rear",
  },
  {
    id: "rear-window",
    number: 18,
    name: "Rear window",
    tagline: "Behind the glass",
    description:
      "A perforated one-way print across the rear glass. Fully visible from outside, invisible from the driver's seat.",
    priceCents: 210000,
    size: "100 × 30 cm",
    tier: "bargain",
    heroView: "rear",
  },
  {
    id: "plate",
    number: 19,
    name: "Licence plate frame",
    tagline: "Your text, road rules permitting",
    description:
      "A custom frame around the rear plate with a line of your choosing. Small, but it is the one people photograph.",
    priceCents: 160000,
    size: "30 × 15 cm",
    tier: "bargain",
    heroView: "rear",
  },
  {
    id: "mirrors",
    number: 20,
    name: "Mirror caps",
    tagline: "A matched pair",
    description: "Both mirror caps, wrapped as a pair. Tiny, but at eye height for every driver I pass.",
    priceCents: 140000,
    size: "2 × 20 × 12 cm",
    tier: "bargain",
    heroView: "front34",
  },
];

const HOUSE_SPONSORS: Record<string, HouseSponsor> = {
  nose: {
    name: "Peptide Ads",
    url: "https://peptideads.com",
    logo: "/sponsors/peptideads-logo.png",
    decal: "/sponsors/peptideads-wordmark-white.png",
    renders: [
      { src: "/renders/cybertruck/wrap-nose-front.jpg", alt: "Peptide Ads decal on the Cybertruck nose panel, front view" },
      { src: "/renders/cybertruck/wrap-nose-front-34.jpg", alt: "Peptide Ads decal on the Cybertruck nose panel, front three-quarter view" },
      { src: "/renders/cybertruck/wrap-nose-detail.jpg", alt: "Close-up of the Peptide Ads cut-vinyl decal on the nose panel" },
    ],
  },
};

export const cybertruck: Car = {
  id: "cybertruck",
  slug: "cybertruck",
  make: "Tesla",
  name: "Tesla Cybertruck",
  shortName: "Cybertruck",
  headline: "Your brand on my Cybertruck.",
  blurb:
    "panels on a stainless steel truck that lives on the road. Pick one, drop your logo on it, pay once, and it rides for as long as the truck does.",
  /** Tesla US configurator, Dual Motor AWD, vehicle price before destination, checked 2026-09-04. */
  priceCents: 7_499_000,
  priceSource: "Tesla's configurator for a Dual Motor AWD Cybertruck",
  views: viewsFor("cybertruck"),
  spots: SPOTS,
  hotspots: CYBERTRUCK_HOTSPOTS,
  house: HOUSE_SPONSORS,
};
